# Generated by Django 3.2.18 on 2023-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentcategory',
            name='users_agent_name_920fc2_idx',
        ),
        migrations.RemoveField(
            model_name='agentcategory',
            name='company',
        ),
        migrations.AddField(
            model_name='companycategory',
            name='agents',
            field=models.ManyToManyField(to='users.AgentCategory'),
        ),
        migrations.AddIndex(
            model_name='agentcategory',
            index=models.Index(fields=['name'], name='users_agent_name_c46bc4_idx'),
        ),
    ]
