# Generated by Django 4.1.5 on 2023-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drivercategory',
            name='users_drive_name_d6c646_idx',
        ),
        migrations.RenameField(
            model_name='drivercategory',
            old_name='passing_rate',
            new_name='en_passing_rate',
        ),
        migrations.AddField(
            model_name='drivercategory',
            name='pscy_passing_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='drivercategory',
            index=models.Index(fields=['name', 'en_passing_rate', 'pscy_passing_rate'], name='users_drive_name_2d2a53_idx'),
        ),
    ]
