# Generated by Django 4.1.5 on 2023-02-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_drivercategory_alter_cretificate_user_and_more'),
        ('users', '0002_remove_drivercategory_users_drive_name_d6c646_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driver_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.drivercategory'),
        ),
        migrations.DeleteModel(
            name='DriverCategory',
        ),
    ]
