# Generated by Django 3.2.18 on 2023-02-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_delete_cretificate'),
        ('users', '0002_auto_20230217_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cretificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_en_score', models.FloatField(default=0)),
                ('final_psyco_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(default='72109C87', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compnay', to='users.companycategory')),
                ('test_attemps', models.ManyToManyField(to='assessments.TestAttempt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cretificate',
            index=models.Index(fields=['user', 'final_en_score', 'final_psyco_score', 'timestamp', 'created_at'], name='users_creti_user_id_94c325_idx'),
        ),
    ]
