# Generated by Django 3.2.18 on 2023-02-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230218_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cretificate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL),
        ),
    ]
