# Generated by Django 3.2.18 on 2023-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_cretificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cretificate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
