# Generated by Django 3.2.18 on 2023-02-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230218_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocies',
            name='comapny',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
