# Generated by Django 3.2.18 on 2023-02-18 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_invocies_comapny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invocies',
            name='comapny',
        ),
        migrations.AddField(
            model_name='invocies',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='invocies',
            name='user',
        ),
        migrations.AddField(
            model_name='invocies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
