# Generated by Django 3.2.18 on 2023-02-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230218_1720'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invocies',
            name='users_invoc_active_193be9_idx',
        ),
        migrations.RemoveField(
            model_name='invocies',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='invocies',
            name='start_date',
        ),
        migrations.AddField(
            model_name='invocies',
            name='type',
            field=models.CharField(choices=[('indvidual', 'indvidual'), ('group', 'group'), ('company', 'company')], default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='invocies',
            index=models.Index(fields=['active', 'company', 'create_by', 'invocies_file', 'timestamp'], name='users_invoc_active_2721e4_idx'),
        ),
    ]
