# Generated by Django 3.2.18 on 2023-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_invocies_users'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invocies',
            name='users_invoc_active_0ca011_idx',
        ),
        migrations.RemoveField(
            model_name='invocies',
            name='invocies_file',
        ),
        migrations.AddIndex(
            model_name='invocies',
            index=models.Index(fields=['active', 'company', 'user', 'type', 'create_by', 'timestamp'], name='users_invoc_active_99d0b8_idx'),
        ),
    ]
