# Generated by Django 3.2.18 on 2023-02-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230218_1933'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invocies',
            name='users_invoc_active_99d0b8_idx',
        ),
        migrations.AddField(
            model_name='invocies',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invocies',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='invocies',
            index=models.Index(fields=['active', 'start_date', 'end_date', 'company', 'user', 'type', 'create_by', 'timestamp'], name='users_invoc_active_e4d683_idx'),
        ),
    ]
