# Generated by Django 3.2.18 on 2023-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230218_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invocies',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invocies',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
