# Generated by Django 4.1.3 on 2023-02-16 12:02

import assessments.models
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cretificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_en_score', models.FloatField(default=0)),
                ('final_psyco_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(default='72109C87', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DriverCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('en_passing_rate', models.PositiveIntegerField(default=0)),
                ('pscy_passing_rate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Psycometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('tutorial_path', models.URLField(blank=True, null=True)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_limit', models.PositiveIntegerField(default=7)),
                ('must', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('audio', 'audio')], default='', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('en', 'en'), ('psyc', 'psyc')], default='', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('english_Questions', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('audio_Questions', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('tutorial_path', models.URLField(blank=True, null=True)),
                ('number_question', models.PositiveIntegerField(default=1)),
                ('maximum_attempts', models.PositiveIntegerField(default=5)),
                ('psycometric_must', models.BooleanField(default=True)),
                ('time_limit', models.PositiveIntegerField(default=7)),
                ('second_chance', models.PositiveIntegerField(default=48)),
                ('do_all_must', models.BooleanField(default=True)),
                ('certificate_image', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('certificate_html', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('descriptions', django_quill.fields.QuillField(blank=True, null=True)),
                ('report_page', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('en', 'en'), ('psyc', 'psyc')], default='', max_length=10)),
                ('final_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_attempts', models.PositiveIntegerField(default=0)),
                ('final_mark', models.CharField(choices=[('passed', 'passed'), ('falied', 'falied'), ('not_taken', 'not_taken')], default='not_taken', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('report_template', models.TextField(null=True)),
                ('test_attemp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.testattempt')),
            ],
        ),
    ]
