# Generated by Django 3.2.8 on 2023-02-04 00:37

import assessments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cretificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_en_score', models.FloatField(default=0)),
                ('final_psyco_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='DriverCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('en_passing_rate', models.PositiveIntegerField(default=0)),
                ('pscy_passing_rate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Psycometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_limit', models.PositiveIntegerField(default=7)),
                ('must', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('audio', 'audio')], default='', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('en', 'en'), ('psyc', 'psyc')], default='', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('english_Questions', models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path)),
                ('number_question', models.PositiveIntegerField(default=1)),
                ('maximum_attempts', models.PositiveIntegerField(default=5)),
                ('psycometric_must', models.BooleanField(default=True)),
                ('time_limit', models.PositiveIntegerField(default=7)),
                ('second_chance', models.PositiveIntegerField(default=48)),
                ('do_all_must', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('en', 'en'), ('psyc', 'psyc')], default='', max_length=10)),
                ('final_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_attempts', models.PositiveIntegerField(default=0)),
                ('final_mark', models.CharField(choices=[('passed', 'passed'), ('falied', 'falied'), ('not_taken', 'not_taken')], default='not_taken', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('psycometric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.psycometric')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.test')),
            ],
        ),
    ]
