# Generated by Django 3.2.8 on 2023-02-04 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name', 'certificate_file', 'type', 'number_question', 'maximum_attempts', 'psycometric_must', 'do_all_must'], name='assessments_name_2ad266_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['name'], name='assessments_name_ca0de1_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='assessments.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddField(
            model_name='psycometric',
            name='category',
            field=models.ManyToManyField(to='assessments.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='psycometric',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddIndex(
            model_name='drivercategory',
            index=models.Index(fields=['name', 'en_passing_rate', 'pscy_passing_rate'], name='assessments_name_10e852_idx'),
        ),
        migrations.AddField(
            model_name='cretificate',
            name='test_attemp',
            field=models.ManyToManyField(to='assessments.TestAttempt'),
        ),
        migrations.AddField(
            model_name='cretificate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', 'type', 'final_score', 'timestamp', 'final_mark', 'created_at', 'psycometric'], name='assessments_user_id_a8e0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['text', 'test', 'type', 'file', 'active'], name='assessments_text_a51afc_idx'),
        ),
        migrations.AddIndex(
            model_name='psycometric',
            index=models.Index(fields=['active', 'test', 'must', 'text', 'file', 'description', 'time_limit'], name='assessments_active_4cbbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='cretificate',
            index=models.Index(fields=['user', 'final_en_score', 'final_psyco_score', 'timestamp', 'created_at'], name='assessments_user_id_de779c_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', 'choice', 'created_at', 'question'], name='assessments_user_id_66f375_idx'),
        ),
    ]
