# Generated by Django 4.1.3 on 2023-02-16 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.companycategory'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='psycometric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.psycometric'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name', 'certificate_image', 'tutorial_path', 'certificate_html', 'type', 'number_question', 'maximum_attempts', 'report_page', 'psycometric_must', 'do_all_must', 'descriptions'], name='assessments_name_48d642_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['name'], name='assessments_name_ca0de1_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='assessments.questioncategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddField(
            model_name='psycometric',
            name='category',
            field=models.ManyToManyField(to='assessments.questioncategory'),
        ),
        migrations.AddField(
            model_name='psycometric',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddIndex(
            model_name='drivercategory',
            index=models.Index(fields=['name', 'fees', 'en_passing_rate', 'pscy_passing_rate'], name='assessments_name_ba0887_idx'),
        ),
        migrations.AddField(
            model_name='cretificate',
            name='test_attemps',
            field=models.ManyToManyField(to='assessments.testattempt'),
        ),
        migrations.AddField(
            model_name='cretificate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='testreport',
            index=models.Index(fields=['user', 'test_attemp', 'type', 'timestamp', 'report_template', 'description'], name='assessments_user_id_fe4d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', 'type', 'final_score', 'timestamp', 'final_mark', 'created_at', 'psycometric'], name='assessments_user_id_a8e0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['text', 'test', 'type', 'file', 'active'], name='assessments_text_a51afc_idx'),
        ),
        migrations.AddIndex(
            model_name='psycometric',
            index=models.Index(fields=['active', 'test', 'must', 'tutorial_path', 'text', 'file', 'description', 'time_limit'], name='assessments_active_041c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='cretificate',
            index=models.Index(fields=['user', 'final_en_score', 'final_psyco_score', 'timestamp', 'created_at'], name='assessments_user_id_de779c_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', 'choice', 'created_at', 'question'], name='assessments_user_id_66f375_idx'),
        ),
    ]
