# Generated by Django 4.1.5 on 2023-01-31 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name', 'file', 'type', 'number_question', 'maximum_attempts', 'psycometric_must', 'do_all_must'], name='assessments_name_b8fa33_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddField(
            model_name='psycometric',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddField(
            model_name='cretificate',
            name='test',
            field=models.ManyToManyField(to='assessments.test'),
        ),
        migrations.AddField(
            model_name='cretificate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', 'type', 'final_score', 'timestamp', 'final_mark', 'created_at', 'psycometric'], name='assessments_user_id_a8e0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['text', 'test', 'type', 'file', 'active'], name='assessments_text_a51afc_idx'),
        ),
        migrations.AddIndex(
            model_name='psycometric',
            index=models.Index(fields=['active', 'test', 'must', 'text', 'category', 'file', 'description', 'time_limit', 'passing_rate'], name='assessments_active_a30914_idx'),
        ),
        migrations.AddIndex(
            model_name='cretificate',
            index=models.Index(fields=['user', 'final_en_score', 'final_psyco_score', 'timestamp', 'current_attempts', 'created_at'], name='assessments_user_id_046aac_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', 'choice', 'created_at', 'question'], name='assessments_user_id_66f375_idx'),
        ),
    ]
