# Generated by Django 3.2.18 on 2023-02-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cretificate',
        ),
    ]
