# Generated by Django 3.2.8 on 2023-02-05 12:50

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='audio_Questions',
            field=models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path),
        ),
    ]
