# Generated by Django 4.1.5 on 2023-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='psycometric',
            name='assessments_active_a30914_idx',
        ),
        migrations.RemoveField(
            model_name='psycometric',
            name='passing_rate',
        ),
        migrations.AddIndex(
            model_name='psycometric',
            index=models.Index(fields=['active', 'test', 'must', 'text', 'category', 'file', 'description', 'time_limit'], name='assessments_active_da1089_idx'),
        ),
    ]
