# Generated by Django 3.2.8 on 2023-02-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_test_audio_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cretificate',
            name='images',
        ),
    ]
