# Generated by Django 4.1.5 on 2023-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_drivercategory_users_drive_name_d6c646_idx_and_more'),
        ('assessments', '0003_remove_psycometric_assessments_active_a30914_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='users.drivercategory'),
        ),
    ]
