# Generated by Django 4.1.5 on 2023-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_drivercategory_users_drive_name_d6c646_idx_and_more'),
        ('assessments', '0004_remove_question_category_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='users.drivercategory'),
        ),
    ]
