# Generated by Django 3.2.8 on 2023-02-05 19:58

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_cretificate_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='certificate_html',
            field=models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path),
        ),
        migrations.AddField(
            model_name='test',
            name='certificate_image',
            field=models.FileField(blank=True, null=True, upload_to=assessments.models.upload_file_path),
        ),
    ]
