# Generated by Django 4.1.5 on 2023-01-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_drivercategory_users_drive_name_d6c646_idx_and_more'),
        ('assessments', '0005_alter_question_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='psycometric',
            name='assessments_active_da1089_idx',
        ),
        migrations.RemoveField(
            model_name='psycometric',
            name='category',
        ),
        migrations.AddIndex(
            model_name='psycometric',
            index=models.Index(fields=['active', 'test', 'must', 'text', 'file', 'description', 'time_limit'], name='assessments_active_4cbbdd_idx'),
        ),
        migrations.AddField(
            model_name='psycometric',
            name='category',
            field=models.ManyToManyField(to='users.drivercategory'),
        ),
    ]
