# Generated by Django 3.2.8 on 2023-02-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_auto_20230205_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='cretificate',
            name='test',
            field=models.ManyToManyField(to='assessments.Test'),
        ),
    ]
