# Generated by Django 3.2.8 on 2023-02-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_cretificate_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cretificate',
            old_name='test_attemp',
            new_name='test_attemps',
        ),
        migrations.RenameField(
            model_name='cretificate',
            old_name='test',
            new_name='tests',
        ),
    ]
