# Generated by Django 4.1.5 on 2023-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_psycometric_assessments_active_da1089_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cretificate',
            name='assessments_user_id_046aac_idx',
        ),
        migrations.RemoveField(
            model_name='cretificate',
            name='current_attempts',
        ),
        migrations.RemoveField(
            model_name='cretificate',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cretificate',
            name='test',
        ),
        migrations.AddIndex(
            model_name='cretificate',
            index=models.Index(fields=['user', 'final_en_score', 'final_psyco_score', 'timestamp', 'created_at'], name='assessments_user_id_de779c_idx'),
        ),
    ]
