# Generated by Django 4.1.5 on 2023-01-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_remove_cretificate_assessments_user_id_046aac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cretificate',
            name='test_attemp',
            field=models.ManyToManyField(null=True, to='assessments.testattempt'),
        ),
    ]
