# Generated by Django 3.2.8 on 2023-02-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_auto_20230205_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cretificate',
            name='tests',
        ),
        migrations.AddField(
            model_name='cretificate',
            name='code',
            field=models.CharField(default='72109C87', max_length=10),
        ),
    ]
