# Generated by Django 3.2.8 on 2023-02-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_auto_20230205_2118'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test',
            name='assessments_name_2ad266_idx',
        ),
        migrations.AddField(
            model_name='test',
            name='tutorial_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name', 'certificate_image', 'certificate_html', 'certificate_file', 'type', 'number_question', 'maximum_attempts', 'psycometric_must', 'do_all_must'], name='assessments_name_58da0f_idx'),
        ),
    ]
