# Generated by Django 4.1.5 on 2023-01-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_cretificate_test_attemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cretificate',
            name='test_attemp',
            field=models.ManyToManyField(to='assessments.testattempt'),
        ),
    ]
