# Generated by Django 4.1.5 on 2023-02-01 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0009_alter_cretificate_test_attemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('en_passing_rate', models.PositiveIntegerField(default=0)),
                ('pscy_passing_rate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cretificate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='drivercategory',
            index=models.Index(fields=['name', 'en_passing_rate', 'pscy_passing_rate'], name='assessments_name_10e852_idx'),
        ),
        migrations.AlterField(
            model_name='psycometric',
            name='category',
            field=models.ManyToManyField(to='assessments.drivercategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='assessments.drivercategory'),
        ),
    ]
