# Generated by Django 3.2.8 on 2023-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_auto_20230205_2153'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='psycometric',
            name='assessments_active_4cbbdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='assessments_name_58da0f_idx',
        ),
        migrations.AddField(
            model_name='psycometric',
            name='tutorial_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='psycometric',
            index=models.Index(fields=['active', 'test', 'must', 'tutorial_path', 'text', 'file', 'description', 'time_limit'], name='assessments_active_041c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name', 'certificate_image', 'tutorial_path', 'certificate_html', 'certificate_file', 'type', 'number_question', 'maximum_attempts', 'psycometric_must', 'do_all_must'], name='assessments_name_42a807_idx'),
        ),
    ]
