# Generated by Django 4.1.5 on 2023-02-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_alter_cretificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='second_chance',
            field=models.PositiveIntegerField(default=48),
        ),
    ]
