# Generated by Django 3.2.8 on 2023-02-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_alter_test_tutorial_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tutorial_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
