# Generated by Django 3.2.8 on 2023-02-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_alter_test_tutorial_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='descriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
