# Generated by Django 3.2.8 on 2023-02-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_test_descriptions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test',
            name='assessments_name_42a807_idx',
        ),
        migrations.AlterField(
            model_name='test',
            name='descriptions',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name', 'certificate_image', 'tutorial_path', 'certificate_html', 'certificate_file', 'type', 'number_question', 'maximum_attempts', 'psycometric_must', 'do_all_must', 'descriptions'], name='assessments_name_fc470a_idx'),
        ),
    ]
