# Generated by Django 4.1.3 on 2023-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('designation', models.CharField(max_length=10, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='author/', verbose_name='Author Profile Image')),
                ('auth_status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Author',
            },
        ),
    ]
